### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by yhahn** [kkaefer/chrono.js#6]
We cool for a new tag/release? I can take care of this if you think things are stable.

**Comment by kkaefer** [comment]
Trying to release 1.0.3, but getting this error from npm:

```
npm ERR! Error sending version data

npm ERR! Error: os_process_error OS process timed out.: chrono/1.0.3/-tag/latest
npm ERR!     at Request._callback (/Users/kkaefer/.nvm/v0.6.10/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:182:12)
npm ERR!     at Request.callback (/Users/kkaefer/.nvm/v0.6.10/lib/node_modules/npm/node_modules/request/main.js:109:22)
npm ERR!     at Request.<anonymous> (/Users/kkaefer/.nvm/v0.6.10/lib/node_modules/npm/node_modules/request/main.js:481:18)
npm ERR!     at Request.emit (events.js:67:17)
npm ERR!     at IncomingMessage.<anonymous> (/Users/kkaefer/.nvm/v0.6.10/lib/node_modules/npm/node_modules/request/main.js:442:16)
npm ERR!     at IncomingMessage.emit (events.js:88:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:137:23)
npm ERR!     at CleartextStream.ondata (http.js:1147:24)
npm ERR!     at CleartextStream._push (tls.js:367:27)
npm ERR!     at SecurePair.cycle (tls.js:688:20)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/Users/kkaefer/.nvm/v0.6.10/bin/npm" "publish"
npm ERR! cwd /Users/kkaefer/Code/v6/chrono.js
npm ERR! node -v v0.6.10
npm ERR! npm -v 1.1.0-3
npm ERR! message os_process_error OS process timed out.: chrono/1.0.3/-tag/latest
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kkaefer/Code/v6/chrono.js/npm-debug.log
```

/cc @isaacs

**Comment by yhahn** [comment]
This happened to me with another package. The workaround was to unpublish each release until the entire package was gone from the registry (assuming the couch doc for the project is deleted at this point) and then republish each tag individually.

Maybe we should hold off on this approach if @isaacs wants to take a look and see what's up?

**Comment by isaacs** [comment]
@kkaefer Can you upload the npm-debug.log file somewhere?

**Comment by kkaefer** [comment]
https://gist.github.com/4a6fb18b29281d12e42e

**Comment by isaacs** [comment]
Thanks.  Pinging @jhs now.

**Comment by springmeyer** [comment]
I'm hitting this now trying to publish `node-eio`:

```
npm ERR! Error sending version data
npm ERR! Error: os_process_error OS process timed out.: eio/0.0.3/-tag/latest
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:180:12)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:99:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:361:18)
npm ERR!     at Request.emit (events.js:64:17)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:327:16)
npm ERR!     at IncomingMessage.emit (events.js:81:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:133:23)
npm ERR!     at CleartextStream.ondata (http.js:1231:22)
npm ERR!     at CleartextStream._push (tls.js:303:27)
npm ERR!     at SecurePair.cycle (tls.js:577:20)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/dane/tmp/node-eio
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.106
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/dane/tmp/node-eio/npm-debug.log
npm not ok
```

npm log: https://gist.github.com/2002505

**Comment by jhs** [comment]
@springmeyer is it working for you now? Thanks.

**Comment by springmeyer** [comment]
@jhs - no, still hanging (latest attempt to publish has been running for ~5 minutes)

**Comment by springmeyer** [comment]
it ultimately died with:

```

npm http PUT https://registry.npmjs.org/eio
npm http 409 https://registry.npmjs.org/eio
npm http GET https://registry.npmjs.org/eio
npm http 200 https://registry.npmjs.org/eio
npm http PUT https://registry.npmjs.org/eio/0.1.0/-tag/latest
npm ERR! Error sending version data

npm ERR! Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:412:26)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/dane/tmp/node-eio
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message SSL Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/dane/tmp/node-eio/npm-debug.log
npm not ok
~/tmp/node-eio[master]$ npm owner ls eio
npm http GET https://registry.npmjs.org/eio
npm http 200 https://registry.npmjs.org/eio
kkaefer <kkaefer@gmail.com>
springmeyer <dane@dbsgeo.com>
tmcw <macwright@gmail.com>
yhahn <young@developmentseed.org>
willwhite <will@developmentseed.org>
```

I am an owner, so I'm not sure what is up.

**Comment by springmeyer** [comment]
just tried again, no dice - still hanges. So I unpublished all of node-eio, and re-published, and that worked.
